# Generated by Django 4.2.28 on 2026-03-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
