# Generated by Django 4.2.28 on 2026-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0005_country_state_city_area_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
