# Generated by Django 4.2.28 on 2026-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0010_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
