# Generated by Django 4.2.28 on 2026-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0013_overallhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('site_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
