# Generated by Django 4.2.28 on 2026-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0014_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
