# Generated by Django 4.2.28 on 2026-03-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censesapp', '0016_volunteerallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('head_name', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=15)),
                ('door_no', models.CharField(max_length=50)),
                ('apartment_name', models.CharField(blank=True, max_length=100)),
                ('flat_no', models.CharField(blank=True, max_length=50)),
                ('floor_no', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('road_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('landline', models.CharField(blank=True, max_length=15)),
                ('residential_status', models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter')], max_length=20)),
                ('ration_card', models.FileField(blank=True, upload_to='ration_cards/')),
                ('no_of_members', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censesapp.area')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('member_type', models.CharField(choices=[('Adult', 'Adult'), ('Student', 'Student'), ('Baby', 'Baby')], max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='censesapp.family')),
            ],
        ),
    ]
