# Generated by Django 4.2.28 on 2026-03-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0017_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.bloodgroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='govt_health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='overall_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.overallhealth'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='member',
            name='private_health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.relationship'),
        ),
    ]
