# Generated by Django 4.2.28 on 2026-03-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0019_member_aadhaar_number_member_academic_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='academic_qualification',
        ),
        migrations.RemoveField(
            model_name='member',
            name='annual_income',
        ),
        migrations.AddField(
            model_name='member',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.income'),
        ),
        migrations.AddField(
            model_name='member',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.qualification'),
        ),
        migrations.AlterField(
            model_name='member',
            name='chronic_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.chronicdisease'),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censesapp.occupation'),
        ),
    ]
