# Generated by Django 4.2.28 on 2026-03-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0020_remove_member_academic_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='product_service_listing_in_yellow_pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
