# Generated by Django 4.2.28 on 2026-03-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0021_alter_member_product_service_listing_in_yellow_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
