# Generated by Django 4.2.28 on 2026-03-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0025_loginreport_delete_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='censesapp.adduser'),
        ),
    ]
