# Generated by Django 4.2.28 on 2026-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0026_adduser_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerAllocation',
        ),
    ]
