# Generated by Django 4.2.28 on 2026-03-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0028_volunteerallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='fullname',
        ),
    ]
