# Generated by Django 4.2.28 on 2026-04-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0033_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='censesapp.family'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
