# Generated by Django 3.2.20 on 2026-04-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0034_alter_member_family_alter_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transferred_to_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_in_members', to='censesapp.family'),
        ),
    ]
