# Generated by Django 3.2.20 on 2026-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censesapp', '0035_auto_20260415_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
